### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by masterDev32** [tgiProject2018/Biomedical#2]
Apres plus de 10 insertion dans la table l'affichage n'est plus clean(background blanc et image pas assez grand) voir capture d'ecran.  
![capture](https://user-images.githubusercontent.com/30531849/37605763-497c967e-2b6a-11e8-8153-d12c921e61ee.PNG)

![capture_2](https://user-images.githubusercontent.com/30531849/37605808-68ad3a62-2b6a-11e8-9448-567f45e85730.PNG)

**Comment by cloud1250x4** [comment]
Fixed in https://github.com/tgiProject2018/Biomedical/commit/7d00faeaacb3af83e29fb223ab8ccd2d817dc977
